### ISSUE TITLE
Problema na apresentação de blocos de código (.cls)

### ISSUE THREAD

**Issue by carolinatanigushi** [hedra-digital/cursotex#3]
No template em classe, não consigo fazer blocos de código serem apresentados da forma correta. Inserindo o código abaixo no latex obtenho o seguinte resultado:

![codigo2](https://cloud.githubusercontent.com/assets/12699183/24249982/0f6898fc-0fb4-11e7-9e1c-9ff722439c43.png)

![codigo1](https://cloud.githubusercontent.com/assets/12699183/24249876/9f89644e-0fb3-11e7-9773-400328000737.png)

Veja como é apresentado na revista atualmente:

![codigo3](https://cloud.githubusercontent.com/assets/12699183/24250097/755a2e78-0fb4-11e7-86b1-6987cb892553.png)

Para esses casos, a marcação do código está feita corretamente ou deveria ter usado algum outro comando/ambiente?

**Comment by jorgesallum** [comment]
Respondi no anterior!.
